import type { RealtyObject } from "@/entities/realty/types/realtyObject";

export const REALTY_LIST: RealtyObject[] = [
  {
    id: 1,
    name: "Modern Apartment",
    description: "A stylish apartment in the center of Kyiv with a balcony.",
    price: 120000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.5234, 50.4501] },
  },
  {
    id: 2,
    name: "Cozy House",
    description: "Family house with a garden in a quiet district.",
    price: 250000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.535, 50.455] },
  },
  {
    id: 3,
    name: "Office Space",
    description: "Spacious office near Khreshchatyk street.",
    price: 320000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.521, 50.448] },
  },
  {
    id: 4,
    name: "Luxury Villa",
    description: "Exclusive villa with pool and private parking.",
    price: 780000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.55, 50.46] },
  },
  {
    id: 5,
    name: "Studio Apartment",
    description: "Compact studio, ideal for students.",
    price: 60000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.50, 50.445] },
  },
  {
    id: 6,
    name: "Townhouse",
    description: "Townhouse in Pechersk district.",
    price: 310000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.54, 50.43] },
  },
  {
    id: 7,
    name: "Penthouse",
    description: "Top-floor penthouse with panoramic city views.",
    price: 450000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.527, 50.457] },
  },
  {
    id: 8,
    name: "Cottage",
    description: "Countryside-style cottage in Holosiiv district.",
    price: 200000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.60, 50.39] },
  },
  {
    id: 9,
    name: "Warehouse",
    description: "Large warehouse with good transport access.",
    price: 180000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.58, 50.49] },
  },
  {
    id: 10,
    name: "Commercial Space",
    description: "Ground-floor shop space near subway.",
    price: 150000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.495, 50.44] },
  },
  {
    id: 11,
    name: "Loft Apartment",
    description: "Trendy loft with high ceilings.",
    price: 170000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.515, 50.453] },
  },
  {
    id: 12,
    name: "Family House",
    description: "Spacious house with three bedrooms.",
    price: 280000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.56, 50.47] },
  },
  {
    id: 13,
    name: "Hotel",
    description: "Small boutique hotel near the center.",
    price: 650000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.525, 50.455] },
  },
  {
    id: 14,
    name: "Office Center",
    description: "Business center with conference rooms.",
    price: 500000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.51, 50.46] },
  },
  {
    id: 15,
    name: "Rural-style House",
    description: "House with wooden finish in city outskirts.",
    price: 95000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.65, 50.42] },
  },
  {
    id: 16,
    name: "Luxury Apartment",
    description: "Elegant apartment with designer renovation.",
    price: 275000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.505, 50.452] },
  },
  {
    id: 17,
    name: "Student Dorm",
    description: "Affordable rooms for students.",
    price: 40000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.59, 50.45] },
  },
  {
    id: 18,
    name: "Resort Cottage",
    description: "Holiday cottage with green surroundings.",
    price: 120000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.62, 50.41] },
  },
  {
    id: 19,
    name: "Duplex",
    description: "Modern duplex near metro.",
    price: 190000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.545, 50.48] },
  },
  {
    id: 20,
    name: "Retail Store",
    description: "Street-facing retail property.",
    price: 130000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.53, 50.445] },
  },
  {
    id: 21,
    name: "Skyscraper Office",
    description: "Office in a skyscraper with city view.",
    price: 420000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.50, 50.455] },
  },
  {
    id: 22,
    name: "Small Apartment",
    description: "Budget apartment near public transport.",
    price: 65000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.54, 50.44] },
  },
  {
    id: 23,
    name: "Farmhouse",
    description: "Farm-style house with land plot.",
    price: 135000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.61, 50.42] },
  },
  {
    id: 24,
    name: "Luxury Mansion",
    description: "Mansion with private park and lake view.",
    price: 1250000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.57, 50.43] },
  },
  {
    id: 25,
    name: "Office Floor",
    description: "Entire floor suitable for IT office.",
    price: 350000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.51, 50.46] },
  },
  {
    id: 26,
    name: "Warehouse Complex",
    description: "Multiple warehouses in one complex.",
    price: 470000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.59, 50.48] },
  },
  {
    id: 27,
    name: "Eco House",
    description: "Energy-efficient eco house.",
    price: 185000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.63, 50.44] },
  },
  {
    id: 28,
    name: "Apartment Complex",
    description: "Investment property with 12 apartments.",
    price: 890000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.53, 50.47] },
  },
  {
    id: 29,
    name: "Seaside Apartment",
    description: "Apartment with terrace and river view.",
    price: 250000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.55, 50.445] },
  },
  {
    id: 30,
    name: "Hostel",
    description: "Budget hostel with 15 rooms.",
    price: 140000,
    location: "Kyiv, Ukraine",
    geometry: { type: "Point", coordinates: [30.515, 50.46] },
  },
];
